name: Maven Release

on:
  release:
    branches: [ v* ]
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
    - uses: nelonoel/branch-name@v1.0.1
    - name: set-branch-name
      run:  echo "::set-output name=branch-name::${BRANCH_NAME}"
    - name: Do Release
      uses: qcastel/github-actions-maven-release@v1.12.5
      env:
        JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/ 
      with:
        release-branch-name: ${{ steps.set-branch-name.outputs.branch-name }}
        git-release-bot-name: ESAStackAdmin
        git-release-bot-email: esa.stack@oppo.com
        maven-repo-server-id: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
        maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
        maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}
        ssh-private-key: ${{ secrets.CI_PRIVATE_KEY }} 
        gpg-key-id: ${{ secrets.CI_GPG_KEY_ID }}
        gpg-key: ${{ secrets.CI_GPG_KEY }}
        gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
        maven-args: "-Dmaven.javadoc.skip=true -Psonatype-oss-release"
